### ISSUE TITLE
Months overlap in "Installs over time" panel under App Statistics on Mobile

### ISSUE THREAD

**Issue by kbdharun** [flathub-infra/website#1875]
![Screenshot_2023-08-30-19-44-19-044_com android chrome](https://github.com/flathub/website/assets/26346867/890546dd-5300-4681-a23c-5c9cfed4772b)

I found this issue to occur in some popular applications, the above screenshot is Bottles in this case.

An alternative can be to move years to next line, or only display 2-3 months and years.

**Comment by razzeee** [comment]
What kind of device with what resolution?

Here is 382 width, which seems fairly small

![image](https://github.com/flathub/website/assets/5943908/3b3b019e-7193-4945-8678-c0002b16e570)

**Comment by kbdharun** [comment]
> What kind of device with what resolution?
> 
> Here is 382 width, which seems fairly small
> 
> ![image](https://github.com/flathub/website/assets/5943908/3b3b019e-7193-4945-8678-c0002b16e570)
> 

The device is Poco X3 Pro and I am sure the resolution is 1080.

I am able to replicate this issue in Firefox too.

**Comment by Maltimore** [comment]
On Desktop the months also don't look good:
![image](https://github.com/flathub-infra/website/assets/10359335/8fbc9273-7175-4433-9b18-ce92d9d1ba6f)

It's not clear which year it is, and one could also do with much fewer labels. I don't know whether this should be a separate issue because it's on desktop browser, or whether the same fix could apply to both desktop and mobile.

**Comment by razzeee** [comment]
Please check again, the charting code has changed.

**Comment by RacerBG** [comment]
I can't reproduce this issue. Looks good to me.

**Comment by kbdharun** [comment]
> Please check again, the charting code has changed. 

Just now checked again, the chart looks fine and all fields are uniformly seperated.
