### ISSUE TITLE
"Verified" badges aren't consistent?

### ISSUE THREAD

**Issue by vizrbo** [flathub-infra/website#2844]
Hello! Browsing through the verified flatpaks on FlatHub, I came across a few peculiarities and would like to learn why this is so.
<br>
<strong>Case 1: The app searched for has a "verified tick" but on the app page has neither got the dev's name nor the "verified badge"</strong>

![image](https://github.com/flathub-infra/website/assets/133123008/b684590b-1aba-48f2-8968-1b009ec9fd12)
![image](https://github.com/flathub-infra/website/assets/133123008/72b908bf-dd66-40bd-801b-de1734a3195d)
<br><br>
<strong>Case 2: The app searched for has a "verified tick" and the app page lists the dev's name but not the "verified badge"</strong>

![image](https://github.com/flathub-infra/website/assets/133123008/fd8b82e3-0a04-4772-b6b7-518c4c440369)
![image](https://github.com/flathub-infra/website/assets/133123008/ea8c1e42-6c8e-4a44-b012-414f387a1882)
<br><br>
<strong>Case 3: The app searched for has a "verified tick" and the app page lists both the dev's name and the "verified badge"</strong>
(which I think is the expected behaviour?)

![image](https://github.com/flathub-infra/website/assets/133123008/b87b4a06-c065-473d-b94f-f5a3812652bd)
![image](https://github.com/flathub-infra/website/assets/133123008/5f238638-864f-4fa9-abef-71883e9c0fcc)

**Comment by bbhtt** [comment]
Case 1 is because they are missing the developer name tag. Next time they rebuild, it'll be caught by the linter.

It's almost been a year since Cheese was rebuilt and the rules for having developer name were enforced a few months ago.

Case 2 is probably some caching issue on the details page. It was verified just three days ago and the page hasn't caught up.

Case 3 is how things should look when everything is ok.

**Comment by razzeee** [comment]
Verification should be back to normal now

**Comment by vizrbo** [comment]
@bbhtt Thanks for the clarification!

@razzeee Indeed! I saw that you pushed a new commit addressing this, thanks 🙂
